on:
  push:
    branches:
      - master
    paths:
      - '{{cookiecutter.service_name}}/**' # Only run the workflow when changes are made to the {{cookiecutter.service_name}} directory

jobs:
  build-sign-and-publish:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: {% raw %}${{ secrets.DOCKERHUB_USERNAME }}{% endraw %}
      SERVICE_NAME: '{{cookiecutter.service_name}}'
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install yq
      run: |
        sudo add-apt-repository ppa:rmescandon/yq -y
        sudo apt-get update -q
        sudo apt-get install yq -y

    - name: Get Version from application-manifest.yaml
      id: get_version
      run: |
        export VERSION=$(yq eval '.version' application-manifest.yaml)
        echo "Version: $VERSION"
        echo "::set-output name=version::$VERSION"

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: {% raw %}${{ secrets.DOCKERHUB_USERNAME }}{% endraw %}
        password: {% raw %}${{ secrets.DOCKERHUB_PASSWORD }}{% endraw %}

    - name: Build Docker Image
      run: |
        docker build -t {% raw %}${{ secrets.DOCKERHUB_USERNAME }}{% endraw %}/{{cookiecutter.service_name}}:{% raw %}${{ steps.get_version.outputs.version }}{% endraw %} ./{{cookiecutter.service_name}}

    - name: Push Signed Docker Image
      run: |
        docker push {% raw %}${{ secrets.DOCKERHUB_USERNAME }}{% endraw %}/{{cookiecutter.service_name}}:{% raw %}${{ steps.get_version.outputs.version }}{% endraw %}
